### PR TITLE
Add replacement sample for white/black list -> allow/block list

### PR DESCRIPTION
**Pull request by corygehr**
Add example usage of 'allow list' and 'block list' as a replacement for 'white list' and 'black list' (in respective order of applicability).

### CODE REVIEW

**Comment by tomresing** [comment]
This seems like a good addition

**Comment by GossiTheDog** [comment]
Could this be merged please?

**Comment by corygehr** [comment]
@mbellthomson what is the process for approving and merging changes in this repo? This has been open for almost two months.

**Comment by pivic** [comment]
> @mbellthomson what is the process for approving and merging changes in this repo? This has been open for almost two months.

Good question. Some of my issues have been closed and when asked why, Microsoft people have said 'we're tracking this internally'.

**Comment by mbellthomson** [comment]
Hello everyone,
Pull requests cannot be merged from the Public Repo as the Style Guide is hosted through a Private-Public Repo configuration. Additionally, all changes must be approved by the Microsoft Editorial Board before being implemented. If you have feedback on how changes should be made to a topic, kindly post these in an Issue instead of a Pull Request so that the information can be reviewed and approved internally. Please let me know if there are any additional questions about this process.  Thank you, Melissa

**Comment by pivic** [comment]
Thanks, @mbellthomson! How would you like feature requests to be logged?

**Comment by pivic** [comment]
@mbellthomson Hi! Is there any chance for you to respond to my question in this issue, regarding feature requests?

**Comment by mbellthomson** [comment]
@pivic,  If you have feedback on how changes should be made to a topic, kindly post these in an Issue instead of a Pull Request so that the information can be reviewed and approved internally. This should also apply for feature requests.

**Comment by pivic** [comment]
@mbellthomson: thank you so much! I'll be sure to do that. Cheers!

**Pull request closed without merging**
